## <font color=[TPL_STATUS_COLOR]> [TPL_REPO_SHORT_NAME] 构建[TPL_BUILD_STATUS] [TPL_STATUS_EMOTICON] </font>

![]([TPL_STATUS_PIC])

当前提交作者名称 [TPL_AUTHOR_NAME]

当前提交作者的用户名 [TPL_AUTHOR_USERNAME]

[[TPL_AUTHOR_NAME]([TPL_AUTHOR_EMAIL])](mailto:[TPL_AUTHOR_EMAIL])

<font color=[TPL_STATUS_COLOR]> [TPL_COMMIT_MSG] - [TPL_COMMIT_BRANCH] </font>

[[TPL_COMMIT_SHA]]([TPL_COMMIT_LINK])

[点击这里查看构建详情]([TPL_BUILD_LINK])