## <font color=[TPL_STATUS_COLOR]> [TPL_REPO_SHORT_NAME] 构建[TPL_BUILD_STATUS] [TPL_STATUS_EMOTICON] </font>

![]([TPL_STATUS_PIC])

<font color=[TPL_STATUS_COLOR]> [TPL_COMMIT_MSG] - [TPL_COMMIT_BRANCH] </font>

[[TPL_COMMIT_SHA]]([TPL_COMMIT_LINK])

[点击这里查看详情]([TPL_BUILD_LINK])