## <font color=[TPL_STATUS_COLOR]> [TPL_REPO_SHORT_NAME] 构建[TPL_BUILD_STATUS] [TPL_STATUS_EMOTICON] </font>

![]([TPL_STATUS_PIC])

[TPL_COMMIT_MSG] - [TPL_COMMIT_BRANCH]

[[TPL_AUTHOR_NAME] ([TPL_AUTHOR_EMAIL])](mailto:[TPL_AUTHOR_EMAIL])

[[TPL_COMMIT_SHA]]([TPL_COMMIT_LINK])

<font color=[TPL_STATUS_COLOR]> [点击这里查看drone构建详情]([TPL_BUILD_LINK]) </font>